"""initial_schema

Revision ID: 31fef99303be
Revises: 
Create Date: 2026-09-24 00:00:30.688023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31fef99303be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_number')
    )
    op.create_index('ix_students_roll_number', 'students', ['roll_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('admin', 'examiner', 'moderator', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'evaluation', 'moderation', 'completed', native_enum=False, create_constraint=True), server_default='draft', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exams_status', 'exams', ['status'], unique=False)
    op.create_table('ai_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.Enum('exam', 'examiner', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('examiner_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['examiner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_summaries_exam_scope_created', 'ai_summaries', ['exam_id', 'scope', 'created_at'], unique=False)
    op.create_table('answer_sheets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('anon_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'mapped', native_enum=False, create_constraint=True), server_default='uploaded', nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_sheets_exam_anon', 'answer_sheets', ['exam_id', 'anon_code'], unique=True)
    op.create_index('uq_sheets_exam_student', 'answer_sheets', ['exam_id', 'student_id'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('question_number', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('max_marks', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('evaluation_mode', sa.Enum('standard', 'reference_grounded', native_enum=False, create_constraint=True), server_default='standard', nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_questions_exam_number', 'questions', ['exam_id', 'question_number'], unique=True)
    op.create_table('results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('total_marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', native_enum=False, create_constraint=True), server_default='draft', nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_results_exam_student', 'results', ['exam_id', 'student_id'], unique=True)
    op.create_table('answer_sheet_pages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('answer_sheet_id', sa.BigInteger(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_pages_sheet_page', 'answer_sheet_pages', ['answer_sheet_id', 'page_number'], unique=True)
    op.create_table('answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('answer_sheet_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('is_attempted', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ocr_status', sa.Enum('pending', 'processing', 'done', 'failed', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ocr_review_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ocr_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verified_text', sa.Text(), nullable=True),
    sa.Column('ocr_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_status', sa.Enum('not_requested', 'pending', 'processing', 'done', 'failed', native_enum=False, create_constraint=True), server_default='not_requested', nullable=False),
    sa.Column('ai_error', sa.Text(), nullable=True),
    sa.Column('assigned_examiner_id', sa.BigInteger(), nullable=True),
    sa.Column('marking_status', sa.Enum('pending', 'marked', 'flagged', 'moderated', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('final_marks', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_source', sa.Enum('examiner', 'moderator', 'system', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_examiner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_answers_exam_ai_status', 'answers', ['exam_id', 'ai_status'], unique=False)
    op.create_index('ix_answers_exam_examiner_status', 'answers', ['exam_id', 'assigned_examiner_id', 'marking_status'], unique=False)
    op.create_index('ix_answers_exam_ocr_status', 'answers', ['exam_id', 'ocr_status'], unique=False)
    op.create_index('ix_answers_exam_question', 'answers', ['exam_id', 'question_id'], unique=False)
    op.create_index('uq_answers_sheet_question', 'answers', ['answer_sheet_id', 'question_id'], unique=True)
    op.create_table('reference_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('doc_type', sa.Enum('official_answer', 'guideline', 'syllabus', 'other', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'indexing', 'indexed', 'failed', native_enum=False, create_constraint=True), server_default='uploaded', nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pinecone_namespace', sa.String(length=50), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ref_docs_exam_status', 'reference_documents', ['exam_id', 'status'], unique=False)
    op.create_index('ix_ref_docs_question', 'reference_documents', ['question_id'], unique=False)
    op.create_table('rubrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('ai_evaluations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('answer_id', sa.BigInteger(), nullable=False),
    sa.Column('mode_requested', sa.Enum('standard', 'reference_grounded', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('mode_used', sa.Enum('standard', 'reference_grounded', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('input_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('suggested_marks', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_marks', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('llm_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('overall_reason', sa.Text(), nullable=True),
    sa.Column('retrieval', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_evaluations_answer_created', 'ai_evaluations', ['answer_id', 'created_at'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('UNCHECKED_ANSWER', 'MISSING_MARKS', 'QUESTION_OUTLIER', 'EXAMINER_DEVIATION', 'AI_DISAGREEMENT', 'TOO_FAST', 'SCORE_SHIFT', 'REPEATED_PATTERN', 'UNVERIFIED_OCR', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('answer_id', sa.BigInteger(), nullable=True),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.Column('examiner_id', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('open', 'dismissed', 'resolved', native_enum=False, create_constraint=True), server_default='open', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['examiner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomalies_exam_status_severity', 'anomalies', ['exam_id', 'status', 'severity'], unique=False)
    op.create_index('ix_anomalies_examiner', 'anomalies', ['examiner_id'], unique=False)
    op.create_index('uq_anomalies_exam_dedupe', 'anomalies', ['exam_id', 'dedupe_key'], unique=True)
    op.create_table('evaluations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('answer_id', sa.BigInteger(), nullable=False),
    sa.Column('examiner_id', sa.BigInteger(), nullable=False),
    sa.Column('ai_evaluation_id', sa.BigInteger(), nullable=True),
    sa.Column('marks_awarded', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('criterion_marks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('ai_accepted', 'ai_modified', 'manual', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', native_enum=False, create_constraint=True), server_default='draft', nullable=False),
    sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('active_seconds', sa.Integer(), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_evaluation_id'], ['ai_evaluations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['examiner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    op.create_index('ix_evaluations_examiner_status', 'evaluations', ['examiner_id', 'status'], unique=False)
    op.create_table('moderations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('answer_id', sa.BigInteger(), nullable=False),
    sa.Column('evaluation_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('original_marks', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('moderated_marks', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('decision', sa.Enum('confirmed', 'overridden', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderations_answer_created', 'moderations', ['answer_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_moderations_answer_created', table_name='moderations')
    op.drop_table('moderations')
    op.drop_index('ix_evaluations_examiner_status', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('uq_anomalies_exam_dedupe', table_name='anomalies')
    op.drop_index('ix_anomalies_examiner', table_name='anomalies')
    op.drop_index('ix_anomalies_exam_status_severity', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index('ix_ai_evaluations_answer_created', table_name='ai_evaluations')
    op.drop_table('ai_evaluations')
    op.drop_table('rubrics')
    op.drop_index('ix_ref_docs_question', table_name='reference_documents')
    op.drop_index('ix_ref_docs_exam_status', table_name='reference_documents')
    op.drop_table('reference_documents')
    op.drop_index('uq_answers_sheet_question', table_name='answers')
    op.drop_index('ix_answers_exam_question', table_name='answers')
    op.drop_index('ix_answers_exam_ocr_status', table_name='answers')
    op.drop_index('ix_answers_exam_examiner_status', table_name='answers')
    op.drop_index('ix_answers_exam_ai_status', table_name='answers')
    op.drop_table('answers')
    op.drop_index('uq_pages_sheet_page', table_name='answer_sheet_pages')
    op.drop_table('answer_sheet_pages')
    op.drop_index('uq_results_exam_student', table_name='results')
    op.drop_table('results')
    op.drop_index('uq_questions_exam_number', table_name='questions')
    op.drop_table('questions')
    op.drop_index('uq_sheets_exam_student', table_name='answer_sheets')
    op.drop_index('uq_sheets_exam_anon', table_name='answer_sheets')
    op.drop_table('answer_sheets')
    op.drop_index('ix_ai_summaries_exam_scope_created', table_name='ai_summaries')
    op.drop_table('ai_summaries')
    op.drop_index('ix_exams_status', table_name='exams')
    op.drop_table('exams')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_students_roll_number', table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
